name: Deploy to Render

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: arlexrush/pdfconverterfront:2.0

    - name: Trigger Deploy on Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        SERVICE_ID: ${{ secrets.YOUR_SERVICE_ID }}
      run: |
        curl -X POST -H "Accept: application/json" -H "Authorization: Bearer $RENDER_API_KEY" \
        -H "Content-Type: application/json" \
        --data '{"clearCache":true}' \
        https://api.render.com/v1/services/$SERVICE_ID/deploys
